Repository armada-ths/ais, pull requests merged in 2023-08, with the labels that each got.

#851 doc: Update contribution
  docs/CONTRIBUTING.md
Labels: documentation

#897 feat: Add FR API
  .vscode/settings.json
  accounting/admin.py
  accounting/api.py
  accounting/api_urls.py
  accounting/migrations/0022_add_child_products_and_no_customer_removal.py
  accounting/migrations/0023_add_category_description.py
  accounting/migrations/0024_add_child_product_model.py
  accounting/models.py
  ais/common/settings.py
  ais/local/settings.py
  api/urls.py
  companies/models.py
  companies/serializers.py
  exhibitors/migrations/0067_add_transport_information_read.py
  exhibitors/models.py
  fair/models.py
  register/api/__init__.py
  register/api/registration/__init__.py
  register/api/registration/cr.py
  register/api/registration/types/__init__.py
  register/api/registration/types/base64image.py
  register/api/registration/types/cr.py
  register/api/registration/types/registration.py
  register/api/registration/types/util.py
  register/api/registration/util.py
  register/api/status.py
  register/api_urls.py
  requirements.txt
  util/__init__.py
Labels: enhancement

#869 feat: Add magic login link
  ais/common/settings.py
  ais/common/urls.py
  api/urls.py
  api/views.py
  requirements.txt
  templates/companies/companies_view.html
  templates/magic_link/error.html
  templates/magic_link/logmein.html
Labels: enhancement

#894 doc: Add echo statements to init-dev-environment script
  init-dev-environment.sh
Labels: maintenance, documentation

#898 Merging of company registration form into the user registration form
  register/urls.py
  register/views.py
  static/images/chevron_down_icon.svg
  static/images/chevron_right_icon.svg
  static/js/stepform.js
  static/registration_style.css
  templates/register/outside/create_user.html
Labels: enhancement
