Repository armada-ths/ais, pull requests merged in 2023-03, with the labels that each got.

#775 feat: Add hijack library and middleware
  ais/common/settings.py
  ais/common/urls.py
  requirements.txt
Labels: enhancement

#766 fix: Disable debug in production
  ais/common/settings.py
  ais/production/settings.py
  requirements.txt
Labels: bug

#779 doc: Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#784 Add check for no company contact for signup log
  register/models.py
Labels: bug

#791 fix: Add 'Head of Business Relations' as a contact card
  register/views.py
Labels: maintenance

#793 fix: Catalog year in 'more info'
  templates/register/inside/registration_initial.html
Labels: maintenance

#802 feat: Add VSCode auto format on save
  .vscode/settings.json
Labels: enhancement, documentation

#800 Add CI formatting job
  .github/workflows/format.yml
  pyproject.toml
Labels: enhancement

#772 doc: Move and update README, CONTRIBUTING, LICENSE
  .github/CODE_OF_CONDUCT.md
  README.md
  docs/CONTRIBUTING.md
  docs/LICENSE.txt
  docs/README.md
  entrypoint.sh
Labels: documentation

#799 fix: Change docker web port from 8080 to 3000
  Dockerfile
  docker-compose.yml
Labels: bug

#788 feat: Parallelize docker build
  .dockerignore
  Dockerfile
Labels: refactor
