Repository armada-ths/ais, pull requests merged in 2023-05, with the labels that each got.

#861 Remove PR name requirement pipeline
  .github/workflows/pr-style.yml
Labels: documentation

#865 feat: Add organization v2 API
  api/serializers.py
  api/urls.py
  api/views.py
Labels: bug, enhancement

#867 fix: Remove sentry logging
  ais/production/settings.py
Labels: bug

#868 fix: Remove allowed hosts
  ais/production/settings.py
Labels: bug

#859 feat: 'Create Company' Redirect Link Style Minor Update
  ais_static/registration_style.css
  templates/register/outside/create_user.html
Labels: enhancement

#871 fix: Fix companies crashing locally
  companies/views.py
  templates/companies/companies_view.html
Labels: bug

#873 fix: Add EB health check plugin
  ais/common/settings.py
  ais/production/settings.py
  requirements.txt
Labels: bug

#876 feat: Add fair dates API
  api/urls.py
  api/views.py
Labels: enhancement

#878 fix: Allow cors for armada.nu
  ais/production/settings.py
Labels: bug

#881 fix: Allow localhost cors
  ais/production/settings.py
Labels: bug
