Repository armada-ths/ais, pull requests merged in 2024-03, with the labels that each got.

#1172 feat: Add API for dashboard registration
  api/urls.py
  api/views.py
  companies/migrations/0032_add_company_type_default.py
  companies/models.py
  dashboard/api/registration/types/serializer.py
  dashboard/urls.py
  dashboard/views.py
  fair/migrations/0024_add_events_dates.py
  fair/migrations/0025_remove_default_registration_acceptance_date_value.py
  fair/models.py
  improved_admin.py
  register/api.py
  register/api_urls.py
  templates/login.html
  templates/register/outside/login_or_register.html
  util/status.py
Labels: bug, improvement

#1180 feat: Add setup script for AIS
  .env.example
  .gitignore
  Makefile
  apps/dashboard/pnpm-lock.yaml
Labels: documentation, internal

#1182 feat: Add dashboard compilation
  .dockerignore
  .gitignore
  Dockerfile
  ais_static/apps/dashboard/assets/Inter-Bold.woff
  ais_static/apps/dashboard/assets/Inter-Bold.woff2
  ais_static/apps/dashboard/assets/Inter-Light.woff
  ais_static/apps/dashboard/assets/Inter-Light.woff2
  ais_static/apps/dashboard/assets/Inter-Medium.woff
  ais_static/apps/dashboard/assets/Inter-Medium.woff2
  ais_static/apps/dashboard/assets/Inter-Regular.woff
  ais_static/apps/dashboard/assets/Inter-Regular.woff2
  ais_static/apps/dashboard/assets/Inter-SemiBold.woff
  ais_static/apps/dashboard/assets/Inter-SemiBold.woff2
  ais_static/apps/dashboard/assets/armada_logo_green.svg
  ais_static/apps/dashboard/assets/color.png
  ais_static/apps/dashboard/assets/index.css
  ais_static/apps/dashboard/assets/index.js
  ais_static/apps/dashboard/assets/primeicons.eot
  ais_static/apps/dashboard/assets/primeicons.svg
  ais_static/apps/dashboard/assets/primeicons.ttf
  ais_static/apps/dashboard/assets/primeicons.woff
  ais_static/apps/dashboard/assets/primeicons.woff2
  ais_static/apps/dashboard/chevron_down_icon.svg
  ais_static/apps/dashboard/index.html
  ais_static/apps/dashboard/vite.svg
  apps/dashboard/package.json
  apps/dashboard/vite.config.ts
Labels: risky, internal

#1187 fix: Change appending output css to asset styles instead of replacing
  apps/dashboard/package.json
Labels: bug, risky
